// Package sqlc contains SQLC generated code.
// This file is a placeholder - run `sqlc generate` to generate actual code.
package sqlc

// DBTX is the interface for database transactions.
type DBTX interface {
	// Methods will be generated by sqlc
}
