// Package sqlc contains SQLC generated code.
// This file is a placeholder - run `sqlc generate` to generate actual code.
package sqlc

// Query functions will be generated by sqlc based on your SQL queries.
